### ISSUE TITLE
Withdraw Fee

### ISSUE THREAD

**Issue by AtHeartEngineer** [Rate-Limiting-Nullifier/rln-contract-v1#5]
The depositor's address should also be mapped to the identity commitment; that way, if that user wants to withdraw from the same address, they can without the fee. If another user wants to withdraw someone's stake ("slash") then the fee will be sent to the fee recipient upon slashing.

**Comment by curryrasul** [comment]
I'll close this issue, I think we'll make a full review after the contract will be ready.
